#include "core/assets/ArchitectureKit.hpp"
#include "core/assets/AssetPack.hpp"
#include <fstream>
#include <iostream>
#include <sstream>
#include <stdexcept>
#include <string>
namespace {core::ArchitectureKind kind(std::string_view s){if(s=="residential")return core::ArchitectureKind::Residential;if(s=="commercial")return core::ArchitectureKind::Commercial;if(s=="factory")return core::ArchitectureKind::Factory;if(s=="farm")return core::ArchitectureKind::Farm;if(s=="mine")return core::ArchitectureKind::Mine;if(s=="port")return core::ArchitectureKind::Port;throw std::runtime_error("unknown architecture kind: "+std::string{s});}}
int main(int argc,char**argv){try{if(argc!=3){std::cerr<<"Usage: core_architecture_cooker <manifest.txt> <out.corearch>\nrows: <kind> <year_min> <year_max> <wealth_min_milli> <wealth_max_milli> <weight> <mesh_key> <material_key> <max_lod>\n";return 2;}std::ifstream in(argv[1]);if(!in)throw std::runtime_error("cannot open architecture manifest");core::ArchitectureKit kit;std::string line;std::uint32_t ln=0;while(std::getline(in,line)){++ln;if(line.empty()||line[0]=='#')continue;std::istringstream row(line);std::string k,mesh,material;unsigned ymin=0,ymax=0,maxlod=0;std::int32_t wmin=0,wmax=0;std::uint32_t weight=0;if(!(row>>k>>ymin>>ymax>>wmin>>wmax>>weight>>mesh>>material>>maxlod)||ymin>65535u||ymax>65535u||maxlod>255u)throw std::runtime_error("bad architecture manifest row "+std::to_string(ln));kit.add({kind(k),static_cast<std::uint16_t>(ymin),static_cast<std::uint16_t>(ymax),wmin,wmax,weight,core::asset_key_hash(mesh),core::asset_key_hash(material),static_cast<std::uint8_t>(maxlod)});}kit.write(argv[2]);const auto check=core::ArchitectureKit::read(argv[2]);if(check.checksum()!=kit.checksum())throw std::runtime_error("architecture cooker readback mismatch");std::cout<<"Core Architecture Cooker PASS\nvariants="<<kit.variants().size()<<"\nchecksum=0x"<<std::hex<<kit.checksum()<<std::dec<<"\n";return 0;}catch(const std::exception&e){std::cerr<<"core_architecture_cooker: "<<e.what()<<'\n';return 1;}}
