#include "core/assets/ArchitectureKit.hpp"
#include <array>
#include <bit>
#include <fstream>
#include <limits>
#include <stdexcept>
#include <type_traits>
namespace core {namespace {
constexpr std::array<char,8> magic{{'C','O','R','E','A','R','0','1'}};constexpr std::uint32_t version=1;constexpr std::uint32_t record_bytes=36;
template<class T>void put(std::ostream&o,T v){using U=std::conditional_t<std::is_signed_v<T>,std::make_unsigned_t<T>,T>;const auto u=std::bit_cast<U>(v);for(std::size_t i=0;i<sizeof(T);++i)o.put(static_cast<char>((static_cast<std::uint64_t>(u)>>(i*8u))&0xffu));if(!o)throw std::runtime_error("architecture kit write failed");}
template<class T>T get(std::istream&i){using U=std::conditional_t<std::is_signed_v<T>,std::make_unsigned_t<T>,T>;std::uint64_t v=0;for(std::size_t n=0;n<sizeof(T);++n){const int c=i.get();if(c<0)throw std::runtime_error("truncated architecture kit");v|=static_cast<std::uint64_t>(static_cast<unsigned char>(c))<<(n*8u);}const auto u=static_cast<U>(v);return std::bit_cast<T>(u);}
}
void ArchitectureKit::add(ArchitectureVariant v){if(v.kind>ArchitectureKind::Port||v.earliest_year>v.latest_year||v.min_wealth_milli>v.max_wealth_milli||v.weight==0||v.max_lod>7u)throw std::invalid_argument("invalid architecture variant");variants_.push_back(v);}
const ArchitectureVariant* ArchitectureKit::select(ArchitectureKind kind,std::uint16_t year,std::int32_t wealth,std::uint64_t seed)const noexcept{std::uint64_t total=0;for(const auto&v:variants_)if(v.kind==kind&&year>=v.earliest_year&&year<=v.latest_year&&wealth>=v.min_wealth_milli&&wealth<=v.max_wealth_milli)total+=v.weight;if(total==0)return nullptr;std::uint64_t pick=seed%total;for(const auto&v:variants_)if(v.kind==kind&&year>=v.earliest_year&&year<=v.latest_year&&wealth>=v.min_wealth_milli&&wealth<=v.max_wealth_milli){if(pick<v.weight)return &v;pick-=v.weight;}return nullptr;}
std::uint64_t ArchitectureKit::checksum()const noexcept{Fnv1a64 h;h.add(variants_.size());for(const auto&v:variants_){h.add(static_cast<std::uint8_t>(v.kind));h.add(v.earliest_year);h.add(v.latest_year);h.add(v.min_wealth_milli);h.add(v.max_wealth_milli);h.add(v.weight);h.add(v.mesh_hash);h.add(v.material_hash);h.add(v.max_lod);}return h.value();}
void ArchitectureKit::write(const std::filesystem::path&path)const{if(variants_.size()>std::numeric_limits<std::uint32_t>::max())throw std::runtime_error("too many architecture variants");std::ofstream o(path,std::ios::binary|std::ios::trunc);if(!o)throw std::runtime_error("cannot create architecture kit");o.write(magic.data(),magic.size());put(o,version);put(o,static_cast<std::uint32_t>(variants_.size()));put(o,checksum());put(o,record_bytes);put(o,std::uint32_t{0});for(const auto&v:variants_){put(o,static_cast<std::uint8_t>(v.kind));put(o,v.max_lod);put(o,std::uint16_t{0});put(o,v.earliest_year);put(o,v.latest_year);put(o,v.min_wealth_milli);put(o,v.max_wealth_milli);put(o,v.weight);put(o,v.mesh_hash);put(o,v.material_hash);}}
ArchitectureKit ArchitectureKit::read(const std::filesystem::path&path){std::ifstream i(path,std::ios::binary);if(!i)throw std::runtime_error("cannot open architecture kit");std::array<char,8> got{};i.read(got.data(),got.size());if(got!=magic)throw std::runtime_error("invalid architecture kit magic");if(get<std::uint32_t>(i)!=version)throw std::runtime_error("unsupported architecture kit version");const auto count=get<std::uint32_t>(i);if(count>1'000'000u)throw std::runtime_error("architecture variant count exceeds cap");const auto expected=get<std::uint64_t>(i);if(get<std::uint32_t>(i)!=record_bytes)throw std::runtime_error("architecture record size mismatch");if(get<std::uint32_t>(i)!=0u)throw std::runtime_error("architecture reserved header field non-zero");ArchitectureKit out;out.variants_.reserve(count);for(std::uint32_t n=0;n<count;++n){ArchitectureVariant v;const auto kind=get<std::uint8_t>(i);if(kind>static_cast<std::uint8_t>(ArchitectureKind::Port))throw std::runtime_error("invalid architecture kind");v.kind=static_cast<ArchitectureKind>(kind);v.max_lod=get<std::uint8_t>(i);if(get<std::uint16_t>(i)!=0u)throw std::runtime_error("architecture reserved record field non-zero");v.earliest_year=get<std::uint16_t>(i);v.latest_year=get<std::uint16_t>(i);v.min_wealth_milli=get<std::int32_t>(i);v.max_wealth_milli=get<std::int32_t>(i);v.weight=get<std::uint32_t>(i);v.mesh_hash=get<std::uint64_t>(i);v.material_hash=get<std::uint64_t>(i);out.add(v);}char extra=0;if(i.get(extra))throw std::runtime_error("trailing architecture kit bytes");if(out.checksum()!=expected)throw std::runtime_error("architecture kit checksum mismatch");return out;}
} // namespace core
